package com.blueocean.web.hellomanage.dao;

import org.apache.ibatis.annotations.Mapper;

import com.blueocean.web.hellomanage.dto.userDo;
@Mapper
public interface userDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Aug 09 13:52:23 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Aug 09 13:52:23 CST 2017
     */
    int insert(userDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Aug 09 13:52:23 CST 2017
     */
    int insertSelective(userDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Aug 09 13:52:23 CST 2017
     */
    userDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Aug 09 13:52:23 CST 2017
     */
    int updateByPrimaryKeySelective(userDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Aug 09 13:52:23 CST 2017
     */
    int updateByPrimaryKey(userDo record);
}